export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const MEDICINE_ROUTE = '/medicines'
export const ILLNES_ROUTE = '/illnes'
export const FAMILY_ROUTE = '/family-member'
export const MEDICINE_USAGE_ROUTE = '/medicine-usage'
export const STATISTICS_ROUTE = '/'