export const medications = [
  'Aspirin',
  'Ibuprofen',
  'Paracetamol',
  'Amoxicillin',
  'Lisinopril',
  'Atorvastatin',
  'Metformin',
  'Omeprazole',
  'Simvastatin',
  'Losartan',
  'Hydrochlorothiazide',
  'Amlodipine',
  'Levothyroxine',
  'Gabapentin',
  'Metoprolol',
  'Prednisone',
  'Escitalopram',
  'Sertraline',
  'Montelukast',
  'Ranitidine',
];

export const medicationTypes = [
  'Analgesic',
  'Antibiotic',
  'Antihypertensive',
  'Antiseptic',
  'Antispasmodic',
  'Antacid',
  'Hypolipidemic Agent',
  'Antidiabetic',
  'Anti-Inflammatory',
  'Antiallergic',
  'Bronchodilator',
  'Antipyretic',
  'Antifungal',
  'Antiviral',
  'Antiemetic',
  'Anticoagulant',
  'Antidepressant',
  'Antipsychotic',
  'Antihistamine',
  'Diuretic',
];